-- ---------------------------------------------
-- ----------- TestME Demo Data DB -------------
-- ---------------------------------------------

CREATE TABLE IF NOT EXISTS `questions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `question` varchar(255) NOT NULL,
  `answers` text NOT NULL,
  `dlevel` int(11) NOT NULL,
  `prive` tinyint(1) NOT NULL,
  `uid` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=83 ;

INSERT INTO `questions` (`id`, `question`, `answers`, `dlevel`, `prive`, `uid`) VALUES
(1, 'Φτάνοντας στο σηματοδότη με ταχύτητα 50 km/h, το φανάρι γίνεται κίτρινο:', '[{"text":"Φρενάρετε δυνατά και σταματάτε σε κάθε περίπτωση.","correct":false},{"text":"Επειδή είστε πολύ κοντά στο σηματοδότη, περνάτε για να αποφύγετε πιθανούς κινδύνους από το απότομο σταμάτημα.","correct":true}]', 2, 0, 2),
(2, 'Λωρίδα επιταχύνσεως συναντάτε μόνο στον αυτοκινητόδρομο:', '[{"text":"Ναι","correct":false},{"text":"Οχι","correct":true}]', 1, 0, 2),
(3, 'Which of the following statements are TRUE about the .NET CLR?', '[{"text":"It provides a language-neutral development & execution environment.","correct":true},{"text":"It ensures that an application would not be able to access memory that it is not authorized to access.","correct":true},{"text":"It provides services to run \\"managed\\" applications.","correct":true},{"text":"The resources are garbage collected.","correct":true},{"text":"It provides services to run \\"unmanaged\\" applications.","correct":false}]', 4, 0, 1),
(4, 'Σε διασταύρωση όπου ο σηματοδότης της πορείας σας δείχνει κόκκινο φως κυκλικής μορφής το οποίο αναβοσβήνει, ποια υποχρέωση έχετε:', '[{"text":"Να ανακόψετε ταχύτητα και να προχωρήσετε με προσοχή.","correct":false},{"text":"Να παραχωρήσετε προτεραιότητα στους πεζούς.","correct":false},{"text":"Να ακινητοποιήσετε το όχημά σας.","correct":true}]', 3, 0, 2),
(5, 'Which of the following are valid .NET CLR JIT performance counters?', '[{"text":"Total memory used for JIT compilation","correct":false},{"text":"Average memory used for JIT compilation","correct":false},{"text":"Number of methods that failed to compile with the standard JIT","correct":true},{"text":"Percentage of processor time spent performing JIT compilation","correct":true},{"text":"Percentage of memory currently dedicated for JIT compilation","correct":false}]', 5, 0, 1),
(6, 'Πινακίδες με μπλε κυκλικό φόντο υποδηλώνουν:', '[{"text":"Υποχρέωση.","correct":true},{"text":"Αναγγελία επικινδύνων θέσεων.","correct":false},{"text":"Απαγόρευση.","correct":false}]', 1, 0, 2),
(7, 'Αν δεν λειτουργούν οι δείκτες αλλαγής κατευθύνσεως (φλας) του οχήματός σας, με ποιο τρόπο θα προειδοποιήσετε ότι έχετε πρόθεση να αλλάξετε κατεύθυνση προς τα αριστερά:', '[{"text":"Εκτείνοντας τον αριστερό βραχίονα.","correct":true},{"text":"Υψώνοντας τον αριστερό βραχίονα κατακόρυφα.","correct":false},{"text":"Χρησιμοποιώντας επανειλημμένα τα φώτα τροχοπεδήσεως.","correct":false}]', 1, 0, 2),
(8, 'Which of the following statements is correct about Managed Code?', '[{"text":"Managed code is the code that is compiled by the JIT compilers.","correct":false},{"text":"Managed code is the code where resources are Garbage Collected.","correct":false},{"text":"Managed code is the code that runs on top of Windows.","correct":false},{"text":"Managed code is the code that is written to target the services of the CLR.","correct":true},{"text":"Managed code is the code that can run on top of Linux.","correct":false}]', 2, 0, 1),
(9, 'Which of the following utilities can be used to compile managed assemblies into processor-specific native code?', '[{"text":"gacutil","correct":false},{"text":"ngen","correct":true},{"text":"sn","correct":false},{"text":"dumpbin","correct":false},{"text":"ildasm","correct":false}]', 4, 0, 1),
(10, 'Προ ισόπεδης σιδηροδρομικής διαβάσεως που επισημαίνεται με φωτεινή σηματοδότηση, ποια υποχρέωση έχετε αν το φως του σηματοδότη είναι ερυθρό που αναβοσβήνει:', '[{"text":"Να διακόψετε τη πορεία σας προ της ειδικής γραμμής ή προ του σηματοδότη αν δεν υπάρχει τέτοια και να παραμείνετε σε στάση μέχρι να σταματήσει να αναβοσβήνει.","correct":true},{"text":"Να σταματήσετε το όχημα πριν από τη διάβαση και να ξεκινήσετε αφού βεβαιωθείτε ότι δεν πλησιάζει σιδηροδρομικός συρμός.","correct":false},{"text":"Να διασχίσετε την ισόπεδη σιδηροδρομική διάβαση χωρίς καθυστέρηση.","correct":false}]', 4, 0, 2),
(11, 'Which of the following are NOT true about .NET Framework?', '[{"text":"It provides a consistent object-oriented programming environment whether object code is stored and executed locally, executed locally but Internet-distributed, or executed remotely.","correct":false},{"text":"It provides a code-execution environment that minimizes software deployment and versioning conflicts.","correct":false},{"text":"It provides a code-execution environment that promotes safe execution of code, including code created by an unknown or semi-trusted third party.","correct":false},{"text":"It provides different programming models for Windows-based applications and Web-based applications.","correct":true},{"text":"It provides an event driven programming model for building Windows Device Drivers.","correct":true}]', 2, 0, 1),
(12, 'Τι καθορίζει μια συνεχής γραμμή σχεδιασμένη σε όλο το πλάτος μιας κατεύθυνσης κυκλοφορίας:', '[{"text":"Προειδοποίηση για προσέγγιση σε άλλο τμήμα οδού, το οποίο παρουσιάζει ιδιαίτερο κίνδυνο.","correct":false},{"text":"Λωρίδα κυκλοφορίας στην οποία η κατεύθυνση της κυκλοφορίας μπορεί να αντιστραφεί.","correct":false},{"text":"Τη θέση προ της οποίας οι οδηγοί είναι υποχρεωμένοι να διακόψουν την πορεία τους λόγω υπάρξεως πινακίδας \\"Υποχρεωτική διακοπή πορείας\\" (STOP) ή κόκκινης ενδείξεως φωτεινού σηματοδότη ή σήματος τροχονόμου ή προ σιδηροδρομικής διαβάσεως.","correct":true}]', 4, 0, 2),
(13, 'Which of the following components of the .NET framework provide an extensible set of classes that can be used by any .NET compliant programming language?', '[{"text":".NET class libraries","correct":true},{"text":"Common Language Runtime","correct":false},{"text":"Common Language Infrastructure","correct":false},{"text":"Component Object Model","correct":false},{"text":"Common Type System","correct":false}]', 1, 0, 1),
(14, 'Τι καθορίζει μια συνεχής κίτρινη γραμμή στο κράσπεδο ή στο άκρο του οδοστρώματος:', '[{"text":"Σε όλο το μήκος της γραμμής και επί της πλευράς αυτής του οδοστρώματος, απαγορεύεται ή υπόκειται σε περιορισμούς η στάθμευση, η οποία υποδεικνύεται με άλλα μέσα.","correct":false},{"text":"Σε όλο το μήκος της και προς τη πλευρά αυτή του οδοστρώματος απαγορεύετα η στάση και η στάθμευση των οχημάτων.","correct":true},{"text":"Σε όλο το μήκος της και προς τη πλευρά αυτή του οδοστρώματος απαγορεύετα η στάση των οχημάτων.","correct":false}]', 3, 0, 2),
(15, 'Which of the following jobs are NOT performed by Garbage Collector?', '[{"text":"Freeing memory on the stack.","correct":true},{"text":"Avoiding memory leaks.","correct":false},{"text":"Freeing memory occupied by unreferenced objects.","correct":false},{"text":"Closing unclosed database collections.","correct":true},{"text":"Closing unclosed files.","correct":true}]', 3, 0, 1),
(16, 'Περιμένοντας εμπρός σε σηματοδότη με κόκκινο φως, πότε μπορείτε να ξεκινήσετε:', '[{"text":"Όταν ο σηματοδότης της κάθετης προς τη πορεία σας διαβάσεως πεζών δείξει κόκκινο φως.","correct":false},{"text":"Όταν ο σηματοδότης δείξει πράσινο φως, παραχωρώντας προτεραιότητα στους κινούμενους (οχήματα, πεζούς) από τη προηγούμενη σηματοδότηση.","correct":true},{"text":"Μόλις διαπιστώσετε ότι η διασταύρωση είναι τελείως ελεύθερη.","correct":false}]', 2, 0, 2),
(17, 'Tom _______ his lecture by the time we get there.', '[{"text":"’s going to have finished","correct":true},{"text":"have finished","correct":false},{"text":"’s going to finish","correct":false},{"text":"''ll finish","correct":false}]', 4, 0, 3),
(18, 'Which of the following statements correctly define .NET Framework?', '[{"text":"It is an environment for developing, building, deploying and executing Desktop Applications, Web Applications and Web Services.","correct":true},{"text":"It is an environment for developing, building, deploying and executing only Web Applications.","correct":false},{"text":"It is an environment for developing, building, deploying and executing Distributed Applications.","correct":false},{"text":"It is an environment for developing, building, deploying and executing Web Services.","correct":false},{"text":"It is an environment for development and execution of Windows applications.","correct":false}]', 1, 0, 1),
(19, 'Ποια διαγράμμιση διαβάσεων πεζών προβλέπει ο Κ.Ο.Κ. και ποιά συμπεριφορά των οδηγών προς τους πεζούς που κινούνται σε αυτές:', '[{"text":"Κίτρινες δέσμες γραμμών και οι οδηγοί πρέπει να προσέχουν μήπως κινούνται πάνω σε αυτές πεζοί, για να αποφύγουν ατύχημα.","correct":false},{"text":"Πλατιές λευκές δεσμίδες παράλληλων γραμμών προ των οποίων οι οδηγοί οφείλουν πάντα να μειώνουν τη ταχήτητα και αν χρειάζεται να σταματούν και να παραχωρούν προτεραιότητα στους πεζούς.","correct":true},{"text":"Ζιγκ - ζαγκ κίτρινη γραμμή και οι οδηγοί παραχωρούν τη προτεραιότητα στους πεζούς.","correct":false}]', 2, 0, 2),
(20, 'Which of the following constitutes the .NET Framework?', '[{"text":"ASP.NET Applications","correct":false},{"text":"CLR","correct":true},{"text":"Framework Class Library","correct":true},{"text":"WinForm Applications","correct":false},{"text":"Windows Services","correct":false}]', 1, 0, 1),
(21, 'Σε ισόπεδη σιδηροδρομική διάβαση που το κόκκινο φως αναβοσβήνει και το κινητό φράγμα δεν έχει κατεβεί ακόμη, πώς συμπεριφέρεστε:', '[{"text":"Συνεχίζετε τη πορεία σας, όσο είναι ακόμη ανοικτό το φράγμα διόδου.","correct":false},{"text":"Περιμένετε εμπρός από τη προειδοποιητική πινακίδα.","correct":true},{"text":"Διασχίζετε τη σιδηροδρομική διάβαση όσο δεν φαίνεται να έρχεται κανένα τρένο.","correct":false}]', 3, 0, 2),
(22, 'Which of the following is the root of the .NET type hierarchy?', '[{"text":"System.Object","correct":true},{"text":"System.Type","correct":false},{"text":"System.Base","correct":false},{"text":"System.Parent","correct":false},{"text":"System.Root","correct":false}]', 1, 0, 1),
(23, 'If you _____ better at speaking in public, the presentation _______ more successful.', '[{"text":"are,will be","correct":false},{"text":"were,would have been","correct":true},{"text":"had been,would have been","correct":true},{"text":"were,would be","correct":false}]', 3, 0, 3),
(24, 'Ένας αστυνομικός ρυθμίζει τη κυκλοφορία σε μία διασταύρωση, στην οποία υπάρχουν επίσης και πινακίδες που ρυθμίζουν τη προτεραιότητα. Πώς συμπεριφέρεστε:', '[{"text":"Ακολουθείτε αποκλειστικά τις πινακίδες που ρυθμίζουν τη προτεραιότητα.","correct":false},{"text":"Ακολουθείτε τα σήματα του αστυνομικού.","correct":true}]', 1, 0, 2),
(25, 'Αν ο τροχονόμος κινεί τη νύχτα ένα κόκκινο φως προς τη κατεύθυνσή σας, ποια υποχρέωση έχετε:', '[{"text":"Να σταματήσετε.","correct":true},{"text":"Να συνεχίσετε τη πορεία σας προς τα εμπρός.","correct":false},{"text":"Να αλλάξετε κατεύθυνση προς τα δεξιά.","correct":false}]', 2, 0, 2),
(26, 'Τα τελευταία 70 χρόνια η κατανάλωση νερού έχει', '[{"text":"δεν έχει αλλάξει καθόλου","correct":false},{"text":"τριπλασιαστεί","correct":false},{"text":"διπλασιαστεί","correct":false},{"text":"εξαπλασιαστεί","correct":true}]', 1, 1, 1),
(27, 'Τι υποχρέωση έχετε στις υποδείξεις τροχονόμων:', '[{"text":"Πρέπει να τις ακολουθείτε όταν συμφωνούν με τη σήμανση.","correct":false},{"text":"Πρέπει να τις ακολουθείτε σε κάθε περίπτωση.","correct":true}]', 1, 0, 2),
(28, 'Τα τελευταία 70 χρόνια ο πληθυσμός της Γης έχει', '[{"text":"διπλασιαστεί","correct":false},{"text":"δεν έχει αλλάξει καθόλου","correct":false},{"text":"τριπλασιαστεί","correct":true},{"text":"εξαπλασιαστεί","correct":false}]', 1, 1, 1),
(29, 'If I _____ my homework,_______ out with my friends?', '[{"text":"will finish,will I go","correct":false},{"text":"finished,could I go","correct":false},{"text":"finish,could I have gone","correct":false},{"text":"finish,can I go","correct":true}]', 1, 0, 3),
(30, 'Στην Ευρώπη απειλούνται ή τελούν υπό εξαφάνιση', '[{"text":"1000 περίπου είδη φυτών","correct":true},{"text":"100 περίπου είδη φυτών","correct":false},{"text":"200 περίπου είδη φυτών","correct":false},{"text":"2000 περίπου είδη φυτών","correct":false}]', 3, 1, 1),
(31, 'Τι πρέπει να κάνουμε για τα απόβλητα των πόλεων;', '[{"text":"να τα πετάμε στις παράνομες χωματερές","correct":false},{"text":"να ενδιαφερόμαστε για την πρόληψη, μείωση, επαναχρησιμοποίηση και ανακύκλωσή τους","correct":true},{"text":"Να μην ενδιαφερόμαστε καθόλου","correct":false},{"text":"να τα ανακυκλώνουμε","correct":false}]', 1, 1, 1),
(32, 'Η Παγκόσμια Ημέρα Περιβάλλοντος έχει θεσπιστεί ως η', '[{"text":"1η Ιουνίου","correct":false},{"text":"5η Ιουνίου","correct":true},{"text":"5η Οκτωβρίου","correct":false},{"text":"6η Ιουλίου","correct":false}]', 2, 1, 1),
(33, 'H θέση ενός κινητού που κινείται σε έναεπίπεδο, προσδιορίζεται κάθε στιγμή αν:', '[{"text":"Είναι γνωστές οι συντεταγμένες τουκινητού (x,y) ως συναρτήσεις του χρόνου","correct":true},{"text":"Είναι γνωστό το διάστημα που διάνυσε τοκινητό.","correct":false}]', 3, 0, 2),
(34, 'Το 2100 η στάθμη της θάλασσας θ'' ανέβει', '[{"text":"περίπου μισό μέτρο","correct":true},{"text":"δε θ'' ανέβει καθόλου","correct":false},{"text":"περίπου ένα μέτρο","correct":false},{"text":"περίπου 20 εκατοστά","correct":false}]', 4, 1, 1),
(35, 'The girl ____ sits next to me at work has a bag just like yours', '[{"text":"who","correct":true},{"text":"which","correct":false},{"text":"(blank)","correct":false},{"text":"whom","correct":false}]', 1, 0, 3),
(36, 'Μία κίνηση λέγεται ευθύγραμμη ομαλή όταν:', '[{"text":"To κινητό κινείται σε ευθεία γραμμή.","correct":false},{"text":"H επιτάχυνση του κινητού είναι σταθερή.","correct":false},{"text":"To κινητό σε ίσους χρόνους διανύει ίσαδιαστήματα","correct":false},{"text":"To κινητό κινείται σε ευθεία γραμμή και ηταχύτητά του είναι σταθερή.","correct":true}]', 4, 0, 2),
(37, 'Το φαινόμενο του θερμοκηπίου είναι', '[{"text":"μια διαδικασία η οποία διατηρεί τη Γη μας δροσερή","correct":false},{"text":"μια φυσική διαδικασία","correct":true},{"text":"μόνο μία τεχνητή διαδικασία","correct":false},{"text":"όλα τα παραπάνω","correct":false}]', 1, 1, 1),
(38, 'H έκφραση 1 m/s2 δηλώνει ότι:', '[{"text":"H απόσταση του κινητού μεταβάλλεταικατά 1m σε κάθε ένα δευτερόλεπτο","correct":false},{"text":"To διάστημα του κινητού μεταβάλλεταικατά 1m σε κάθε ένα δευτερόλεπτο.","correct":false},{"text":"H ταχύτητα του κινητού μεταβάλλεται κατά1 m/s σε κάθε ένα δευτερόλεπτο.","correct":true},{"text":"Τίποτα από τα παραπάνω.","correct":false}]', 2, 0, 2),
(39, 'The man _____ is wearing the blue suit is my brother.', '[{"text":"whom","correct":false},{"text":"that","correct":false},{"text":"who","correct":true},{"text":"(blank)","correct":false}]', 1, 1, 3),
(40, 'Για την αντιμετώπιση της θαλάσσιας ρύπανσης, η χώρα μας', '[{"text":"δεν επιβάλει ποινικές κυρώσεις","correct":false},{"text":"έχει υιοθετήσει και επικυρώσει τις Διεθνείς Συμβάσεις που αφορούν την προστασία της θάλασσας","correct":false},{"text":"έχει δική της νομοθεσία για την πρόληψη και την καταπολέμηση της θαλάσσιας ρύπανσης","correct":false},{"text":"έχει υιοθετήσει και επικυρώσει τις Διεθνείς Συμβάσεις που αφορούν την προστασία της θάλασσας και έχει δική της νομοθεσία για την πρόληψη και την καταπολέμηση της θαλάσσιας ρύπανσης","correct":true}]', 5, 1, 1),
(41, 'To διάστημα που διανύει ένα σώμα, αυξάνεται ανάλογα με το τετράγωνο του χρόνου. Η κίνησηπου κάνει το σώμα είναι:', '[{"text":"Ευθύγραμμη ομαλή.","correct":false},{"text":"Ευθύγραμμη ομαλά επιταχυνόμενη χωρίςαρχική ταχύτητα.","correct":true},{"text":"Ευθύγραμμη ομαλά επιβραδυνόμενη","correct":false},{"text":"Τίποτα από τα παραπάνω.","correct":false}]', 1, 0, 2),
(42, 'Τα μολυσμένα νερά και οι κακές συνθήκες υγιεινής σκοτώνουν ετησίως', '[{"text":"8 εκατομμύρια ανθρώπους","correct":false},{"text":"1 εκατομμύριο ανθρώπους","correct":false},{"text":"2 εκατομμύρια ανθρώπους","correct":false},{"text":"12 εκατομμύρια ανθρώπους","correct":true}]', 2, 1, 1),
(43, 'H ταχύτητα ενός κινητού που κάνει ευθύγραμμη κίνησηελαττώνεται μέχρι να μηδενιστεί. Μετά το κινητόσυνεχίζει την κίνησή του σε αντίθετη κατεύθυνση.To διάστημα που διανύει το κινητό συνέχεια αυξάνεται.', '[{"text":"Σωστό","correct":true},{"text":"Λάθος","correct":false}]', 1, 0, 2),
(44, 'The book ___ you lent me is really good.', '[{"text":"that","correct":true},{"text":"which","correct":true},{"text":"where","correct":false},{"text":"(blank)","correct":true}]', 2, 0, 3),
(45, 'Η τρύπα του όζοντος είναι', '[{"text":"μια απλή τρύπα","correct":false},{"text":"η αιτία της μόλυνσης του περιβάλλοντος","correct":false},{"text":"το αποτέλεσμα της μόλυνσης του περιβάλλοντος","correct":true},{"text":"κάτι που δεν πρέπει να μας ανησυχεί","correct":false}]', 1, 1, 1),
(46, 'To ταχύμετρο ενός αυτοκινήτου δείχνει:', '[{"text":"Την τιμή της στιγμιαίας ταχύτητας.","correct":true},{"text":"Την τιμή της μέσης ταχύτητας","correct":false},{"text":"Την ταχύτητα του αυτοκινήτου σε τιμή καικατεύθυνση.","correct":false},{"text":"Τίποτα από τα παραπάνω.","correct":false}]', 1, 0, 2),
(47, 'In which sentence can you delete who?', '[{"text":"The man who I saw on the bus is my neighbour.","correct":true},{"text":"The man who lives next to me is nearly eighty.","correct":false},{"text":"The man who cleans my windows has gone into hospital.","correct":false}]', 1, 0, 3),
(48, 'O χιλιομετρητής ενός αυτοκινήτου δείχνει 24.532km. H ένδειξη αυτή αντιπροσωπεύει.', '[{"text":"Τη συνολική μετατόπιση του αυτοκινήτου.","correct":false},{"text":"To συνολικό διάστημα που έχει διανύσει τοαυτοκίνητο.","correct":true},{"text":"Κατά μέσο όρο τη μετατόπιση τουαυτοκινήτου.","correct":false},{"text":"Τίποτα από τα παραπάνω.","correct":false}]', 2, 0, 2),
(49, 'In which sentence can you NOT delete that?', '[{"text":"I’ve lost the magazine that I was reading.","correct":false},{"text":"A photocopier is a machine that makes copies of pages.","correct":true},{"text":"The film that we saw yesterday was brilliant.","correct":false}]', 2, 0, 3),
(50, 'By November, we’ll ____ here for five years.', '[{"text":"have been living","correct":true},{"text":"live","correct":false},{"text":"be living","correct":false}]', 3, 0, 3),
(51, 'If he ___ you an invoice, you should pay him.', '[{"text":"''s sent","correct":true},{"text":"would send","correct":false},{"text":"had sent","correct":false}]', 2, 0, 3),
(52, 'O οδηγός ενός αυτοκινήτου φρενάρει όταν βλέπει ναανάβει το πορτοκαλί φως στο σηματοδότη ενός δρόμου:H επιτάχυνση και η ταχύτητα έχουν αντίθετη φορά.', '[{"text":"Σωστο","correct":true},{"text":"Λαθος","correct":false}]', 2, 0, 2),
(53, 'O οδηγός ενός αυτοκινήτου φρενάρει όταν βλέπει ναανάβει το πορτοκαλί φως στο σηματοδότη ενός δρόμου:H επιτάχυνση και η ταχύτητα έχουν την ίδια φορά.', '[{"text":"Σωστό","correct":false},{"text":"Λάθος","correct":true}]', 1, 0, 2),
(54, 'Which sentence is correct?', '[{"text":"If you’d remembered to bring a map, we wouldn’t have been lost now.","correct":false},{"text":"If you remembered to bring a map, we wouldn’t be lost now.","correct":false},{"text":"If you’d remembered to bring a map, we wouldn’t be lost now.","correct":true}]', 1, 0, 3),
(55, 'O οδηγός ενός αυτοκινήτου φρενάρει όταν βλέπει ναανάβει το πορτοκαλί φως στο σηματοδότη ενός δρόμου:H επιτάχυνση έχει ίδια φορά με τη μεταβολή της ταχύτητας', '[{"text":"Σωστό","correct":true},{"text":"Λαθος","correct":false}]', 2, 0, 2),
(56, 'O οδηγός ενός αυτοκινήτου φρενάρει όταν βλέπει να ανάβει τοπορτοκαλί φως στο σηματοδότη ενός δρόμου:H επιτάχυνση έχει αντίθετη φορά με τη μεταβολή της ταχύτητας.', '[{"text":"Σωστο","correct":false},{"text":"Λαθος","correct":true}]', 1, 0, 2),
(57, 'Type Hinting was introduced in which version of PHP?', '[{"text":"PHP 4","correct":false},{"text":"PHP 5","correct":true},{"text":"PHP 5.3","correct":false},{"text":"PHP 6","correct":false},{"text":"PHP 7","correct":false}]', 3, 0, 1),
(58, 'I wish I ____ come to the zoo with you next weekend, but I’m going to be busy.', '[{"text":"will","correct":false},{"text":"had","correct":false},{"text":"could","correct":true}]', 1, 0, 3),
(59, 'Which one of the following is the right way of defining a function in PHP?', '[{"text":"function { function body }","correct":false},{"text":"data type functionName(parameters) { function body }","correct":false},{"text":"functionName(parameters) { function body }","correct":false},{"text":"function fumctionName(parameters) { function body }","correct":true}]', 1, 0, 1),
(60, 'Which of the following are correct ways of creating an array?', '[{"text":"state[0] = “karnataka”;","correct":false},{"text":"$state[] = array(“karnataka”);","correct":false},{"text":"$state[0] = “karnataka”;","correct":true},{"text":"$state = array(“karnataka”);","correct":true}]', 2, 0, 1),
(61, 'A vehicle that takes people to and from hospitals.', '[{"text":"pill","correct":false},{"text":"ambulance","correct":true},{"text":"recover","correct":false},{"text":"injection","correct":false}]', 2, 0, 3),
(62, 'Which function can be used to move the pointer to the previous array position?', '[{"text":"last()","correct":false},{"text":"before()","correct":false},{"text":"prev()","correct":true},{"text":"previous()","correct":false}]', 1, 0, 1),
(63, 'Which function returns an array consisting of associative key/value pairs?', '[{"text":"count()","correct":false},{"text":"array_count()","correct":false},{"text":"array_count_values()","correct":true},{"text":"count_values()","correct":false}]', 1, 0, 1),
(64, 'A rise in the temperature of the body, frequently a symptom of infection.', '[{"text":"pill","correct":false},{"text":"headache","correct":false},{"text":"fever","correct":true}]', 1, 0, 3),
(65, 'The practice of separating the user from the true inner workings of an application through well-known interfaces is known as.', '[{"text":"Polymorphism","correct":false},{"text":"Inheritance","correct":false},{"text":"Encapsulation","correct":true},{"text":"Abstraction","correct":false}]', 2, 0, 1),
(66, 'Which of the following term originates from the Greek language that means “having multiple forms,” defines OOP’s ability to redefine, a class’s characteristics?', '[{"text":"Abstraction","correct":false},{"text":"Polymorphism","correct":true},{"text":"Inheritance","correct":false},{"text":"Differential","correct":false}]', 4, 0, 1),
(67, 'Which of the following is/are an external data?', '[{"text":"Cookies","correct":true},{"text":"Input data from a form","correct":true},{"text":"Server Variables","correct":true},{"text":"Web services data","correct":true},{"text":"None of the mentioned","correct":false},{"text":"All of the mentioned","correct":true}]', 1, 0, 1),
(68, 'Energy made available by the flow of electric charge through a conductor.', '[{"text":"electricity","correct":true},{"text":"electric","correct":false},{"text":"electronic","correct":false}]', 2, 0, 3),
(69, 'Which one of the following filter is used to filter several variables with the same or different filters?', '[{"text":"filter_var_array()","correct":true},{"text":"filter_var()","correct":false},{"text":"filter_input","correct":false},{"text":"filter_input_array","correct":false}]', 2, 0, 1),
(70, 'Which one of the following databases has PHP supported almost since the beginning?', '[{"text":"Oracle Database","correct":false},{"text":"SQL","correct":false},{"text":"SQL+","correct":false},{"text":"MySQL","correct":true}]', 3, 0, 1),
(71, 'Characteristic of elementary school or elementary education.', '[{"text":"essay","correct":false},{"text":"intermediate","correct":false},{"text":"elementary","correct":true}]', 1, 0, 3),
(72, 'Η αεριώδης μάζα που περιβάλλει τη Γη ονομάζεται:', '[{"text":"Λιθόσφαιρα","correct":false},{"text":"Ατμόσφαιρα","correct":true},{"text":"Υδρόσφαιρα","correct":false},{"text":"Βιόσφαιρα","correct":false}]', 3, 1, 3),
(73, 'Νοητοί κύκλοι κάθετοι στον άξονα της Γης ονομάζονται:', '[{"text":"παράλληλοι","correct":false},{"text":"συντεταγμένες","correct":false},{"text":"μεσημβρινοί","correct":true},{"text":"ισημερινοί","correct":false}]', 2, 0, 3),
(74, 'Ποιά είναι η πρωτεύουσα της Ισλανδίας;', '[{"text":"Δουβλίνο","correct":false},{"text":"Τάλιν","correct":false},{"text":"Ρίγα","correct":false},{"text":"Ρέικιαβικ","correct":true}]', 5, 0, 3),
(75, 'Ποιά είναι η πρωτεύουσα της Αυστρίας;', '[{"text":"Βερολίνο","correct":false},{"text":"Βουδαπέστη","correct":false},{"text":"Βιέννη","correct":true},{"text":"Βουλουρέστι","correct":false}]', 4, 0, 3),
(76, 'Ποιά είναι η πρωτεύουσα της Νορβηγίας;', '[{"text":"Στοκχόλμη","correct":false},{"text":"Ελσίνκι","correct":false},{"text":"Όσλο","correct":true},{"text":"Κοπενχάγη","correct":false}]', 4, 1, 3),
(79, 'Το εύκρατο κλίμα:', '[{"text":"επικρατεί σε μεγάλο υψόμετρο.","correct":false},{"text":"έχει μεγάλλες εναλλαγές θερμοκρασίας.","correct":false},{"text":"είναι το πιο κατάλληλο για την ανθρώπινη ζωή.","correct":true}]', 1, 1, 3),
(80, 'Το κλίμα του ισημερινού χαρακτηρίζεται από:', '[{"text":"υπερβολική υγρασία.","correct":true},{"text":"πολυ χαμηλές θερμοκρασίες.","correct":false},{"text":"πολύ υψηλές θερμοκρασίες.","correct":true}]', 4, 1, 3),
(81, 'Φυσικοί πόροι είναι οι:', '[{"text":"ηλιακή ενέργεια","correct":true},{"text":"τεχνολογία","correct":false},{"text":"μεταλλεύματα","correct":true},{"text":"φράγματα","correct":false},{"text":"πετρέλαιο","correct":true},{"text":"πλαστικό","correct":false}]', 5, 0, 3),
(82, 'Ποιά πολιτεία δεν διαρρέει ο ποταμός Κολοράντο;', '[{"text":"Τέξας","correct":true},{"text":"Αριζόνα","correct":false},{"text":"Γιούτα","correct":false},{"text":"Νεβάδα","correct":false},{"text":"Νέο Μεξικό","correct":false}]', 5, 0, 3);


CREATE TABLE IF NOT EXISTS `tags` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nametag` varchar(255) NOT NULL,
  `qid` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `nametag` (`nametag`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=196 ;

INSERT INTO `tags` (`id`, `nametag`, `qid`) VALUES
(1, 'κοκ', 1),
(2, 'ταχύτητα', 1),
(3, 'κοκ', 2),
(4, 'αυτοκινητόδρομος', 2),
(5, '.net', 3),
(6, 'clr', 3),
(7, 'κοκ', 4),
(8, 'διασταύρωση', 4),
(9, '.net', 5),
(10, 'clr', 5),
(11, 'κοκ', 6),
(12, 'πινακίδες', 6),
(13, 'κοκ', 7),
(14, 'φλας', 7),
(15, '.net', 8),
(16, 'managed', 8),
(17, 'code', 8),
(18, 'assemblies', 9),
(19, 'native', 9),
(20, 'code', 9),
(21, 'κοκ', 10),
(22, 'φωτεινός', 10),
(23, 'σηματοδότης', 10),
(24, '.net', 11),
(25, 'framework', 11),
(26, 'κοκ', 12),
(27, 'κυκλοφορίας', 12),
(28, '.net', 13),
(29, 'framework', 13),
(30, 'programming', 13),
(31, 'κοκ', 14),
(32, 'οδόστρωμα', 14),
(33, 'garbage', 15),
(34, 'collector', 15),
(35, 'programming', 15),
(36, 'κοκ', 16),
(37, 'φως', 16),
(38, 'english', 17),
(39, 'grammar', 17),
(40, 'b2', 17),
(41, '.net', 18),
(42, 'framework', 18),
(43, 'κοκ', 19),
(44, 'διάβαση', 19),
(45, '.net', 20),
(46, 'framework', 20),
(47, 'κοκ', 21),
(48, 'φως', 21),
(49, 'σιδηροδρομική', 21),
(50, 'διάβαση', 21),
(51, '.net', 22),
(52, 'programming', 22),
(53, 'english', 23),
(54, 'grammar', 23),
(55, 'b2', 23),
(56, 'κοκ', 24),
(57, 'κυκλοφορίας', 24),
(58, 'κοκ', 25),
(59, 'τροχονόμος', 25),
(60, 'περιβάλλον', 26),
(61, 'νερό', 26),
(62, 'κοκ', 27),
(63, 'τροχονόμος', 27),
(64, 'γη', 28),
(65, 'περιβάλλον', 28),
(66, 'english', 29),
(67, 'grammar', 29),
(68, 'b2', 29),
(69, 'ευρώπη', 30),
(70, 'εξαφάνιση', 30),
(71, 'φυτά', 30),
(72, 'περιβάλλον', 31),
(73, 'απόβλητα', 31),
(74, 'περιβάλλον', 32),
(75, 'παγκόσμια', 32),
(76, 'ημέρα', 32),
(77, 'φυσική', 33),
(78, 'περιβάλλον', 34),
(79, 'θάλλασα', 34),
(80, 'english', 35),
(81, 'grammar', 35),
(82, 'b2', 35),
(83, 'φυσική', 36),
(84, 'κίνηση', 36),
(85, 'περιβάλλον', 37),
(86, 'φαινόμενο', 37),
(87, 'θερμοκηπίου', 37),
(88, 'φυσική', 38),
(89, 'έκφραση', 38),
(93, 'περιβάλλον', 40),
(94, 'ρύπανση', 40),
(95, 'θάλλασα', 40),
(96, 'φυσική', 41),
(97, 'χρόνος', 41),
(98, 'παγκόσμια', 42),
(99, 'μόλυνση', 42),
(100, 'νερό', 42),
(101, 'υγεία', 42),
(102, 'φυσική', 43),
(103, 'ταχύτητα', 43),
(104, 'english', 44),
(105, 'grammar', 44),
(106, 'b2', 44),
(107, 'περιβάλλον', 45),
(108, 'τρύπα', 45),
(109, 'όζοντος', 45),
(110, 'μόλυνση', 45),
(111, 'φυσική', 46),
(112, 'αυτοκίνητο', 46),
(113, 'english', 47),
(114, 'grammar', 47),
(115, 'b2', 47),
(116, 'φυσική', 48),
(117, 'ταχύτητα', 48),
(118, 'english', 49),
(119, 'grammar', 49),
(120, 'b2', 49),
(121, 'english', 50),
(122, 'grammar', 50),
(123, 'b2', 50),
(124, 'english', 51),
(125, 'grammar', 51),
(126, 'b2', 51),
(127, 'φυσική', 52),
(128, 'αυτοκίνητο', 52),
(129, 'φυσική', 53),
(130, 'αυτοκίνητο', 53),
(131, 'english', 54),
(132, 'grammar', 54),
(133, 'b2', 54),
(134, 'φυσική', 55),
(135, 'αυτοκίνητο', 55),
(136, 'φυσική', 56),
(137, 'αυτοκίνητο', 56),
(138, 'php', 57),
(139, 'types', 57),
(140, 'english', 58),
(141, 'grammar', 58),
(142, 'b2', 58),
(143, 'php', 59),
(144, 'framework', 59),
(145, 'php', 60),
(146, 'arrays', 60),
(147, 'english', 61),
(148, 'vocabulary', 61),
(149, 'health', 61),
(150, 'a2', 61),
(151, 'php', 62),
(152, 'arrays', 62),
(153, 'functions', 62),
(154, 'php', 63),
(155, 'arrays', 63),
(156, 'english', 64),
(157, 'vocabulary', 64),
(158, 'health', 64),
(159, 'a2', 64),
(160, 'php', 65),
(161, 'oop', 65),
(162, 'php', 66),
(163, 'oop', 66),
(164, 'php', 67),
(165, 'filter', 67),
(166, 'english', 68),
(167, 'vocabulary', 68),
(168, 'appliances', 68),
(169, 'a2', 68),
(170, 'php', 69),
(171, 'filter', 69),
(172, 'php', 70),
(173, 'database', 70),
(174, 'english', 71),
(175, 'vocabulary', 71),
(176, 'education', 71),
(177, 'γεωγραφία', 72),
(178, 'γεωγραφία', 73),
(179, 'γεωγραφία', 74),
(180, 'πρωτεύουσες', 74),
(181, 'γεωγραφία', 75),
(182, 'πρωτεύουσες', 75),
(183, 'γεωγραφία', 76),
(186, 'πρωτεύουσες', 76),
(189, 'γεωγραφία', 79),
(190, 'γεωγραφία', 80),
(191, 'γεωγραφία', 81),
(192, 'γεωγραφία', 82),
(193, 'english', 39),
(194, 'grammar', 39),
(195, 'b2', 39);


CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user` varchar(255) NOT NULL,
  `pass` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `securitycode` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

INSERT INTO `users` (`id`, `user`, `pass`, `email`, `securitycode`) VALUES
(1, 'Hli4S', 'fe01ce2a7fbac8fafaed7c982a04e229', 'demo@email.com', 'fe01ce2a7fbac8fafaed7c982a04e229'),
(2, 'nestoras1', '81dc9bdb52d04dc20036dbd8313ed055', 'nestoras1@gmail.com', '81dc9bdb52d04dc20036dbd8313ed055'),
(3, 'Evi', '485048aacfbcffef33ef5a57c9cc25dc', 'evi@email.com', '49c0b9d84c2a16fcaf9d25694fda75e1'),
(5, 'John', '9e77d27fa576ee6a5d5beb433b717375', 'John@mail.com', '23734cd52ad4a4fb877d8a1e26e5df5f');